version: "3"

services:
  baseimage:
    build:
      context: ./baseimage
      dockerfile: Dockerfile-base
  gitserver:
    image: gogs/gogs
    volumes:
      - "./gitserver_data:/data"
    ports:
      - "10022:22"
      - "3000:3000"
  jenkins:
    build:
      context: ./jenkins_setup
      dockerfile: Dockerfile
    volumes:
      - "./jenkins_data:/var/jenkins_home"
    environment:
      - JENKINS_PORT="8080"
    ports:
      - "8080:8080"
      - "50000:50000"
