# -*- mode: ruby -*-
# vi: set ft=ruby :

# official box at:  https://app.vagrantup.com/ubuntu/boxes/xenial64

$setupJenkins=<<SCRIPT
sudo apt-get -y update
sudo apt-get install -y default-jdk
wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get -y update
sudo apt-get install -y jenkins
SCRIPT

$setupTomcat=<<SCRIPT
sudo apt-get -y update
sudo apt-get install -y default-jdk
sudo groupadd tomcat
sudo useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
curl -O http://apache.mirrors.ionfish.org/tomcat/tomcat-8/v8.5.30/bin/apache-tomcat-8.5.30.tar.gz
sudo mkdir /opt/tomcat
sudo tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
cd /opt/tomcat
sudo chgrp -R tomcat /opt/tomcat
sudo chmod -R g+r conf
sudo chmod g+x conf
sudo chown -R tomcat webapps/ work/ temp/ logs/
sudo update-java-alternatives -l
echo "test"
SCRIPT
 
node = [
  { :hostname => 'Jenkinssrv', :ip => '192.168.0.42', :box => 'ubuntu/xenial64', :ram => 2000, 
  :port => 8000, 
  :provision => $setupJenkins},
  { :hostname => 'Tomcatssrv', :ip => '192.168.0.43', :box => 'ubuntu/xenial64', :ram => 514, 
  :port => 8000, 
  :provision => $setupTomcat}
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip]
      memory = node[:ram] ? node[:ram] : 256;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "100",
          "--memory", memory.to_s,
        ]
      end
      nodeconfig.vm.provision :shell, inline: $setupJenkins
      nodeconfig.vm.network "forwarded_port", guest: 8000, host: node[:port] 
    end       
end
